# Generated by Django 5.0.2 on 2024-03-18 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EXEplorer', '0002_scannednumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='carbonFootfrint',
            field=models.IntegerField(default=5),
        ),
    ]
