# Generated by Django 5.0.2 on 2024-03-20 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EXEplorer', '0005_tools_tree_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='next_pet_appearance',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pet_visible',
            field=models.BooleanField(default=True),
        ),
    ]
